CC = gcc


# Make stop while the shell command failed (return a non-zero value)
all:
	@echo "$(CC) -Wall -c foo.c"
	@echo "$(CC) -Wall -c bar.c"
	@false
	@echo "$(CC) -Wall -c qux.c"

clean:

success:
	- @ls -l main.c && echo "(success return 0)"

failure:
	- @ls -l hello.c || echo "(failure return 1)"


.PHONY: clean
