CC = gcc


# Make stop while the shell command failed (return a non-zero value)
all: foo.o bar.o qux.o
	@echo "$(CC) -Wall -c foo.c"
	@echo "$(CC) -Wall -c bar.c"
	@false
	@echo "$(CC) -Wall -c qux.c"

clean:


.PHONY: clean
