PWD = $(shell pwd)


# string substitute
TEXT_IN  = $(PWD)
FROM     = $(notdir $(PWD))
TO       = substitute
TEXT_OUT = $(subst $(FROM),$(TO),$(TEXT_IN))


all:
	@echo "([1;33msubst[0m <from>,<to>,<text>)"
	@echo "$(TEXT_IN) -> $(TEXT_OUT)"
	@echo ""

