ARCH = arm64

all:
ifeq ($(ARCH), x86)
	@echo "32-bit x86 platform"
else ifeq ($(ARCH), x86_64)
	@echo "64-bit x86 platform"
else ifeq ($(ARCH), arm)
	@echo "32-bit ARM platform"
else ifeq ($(ARCH), arm64)
	@echo "64-bit ARM platform"
else ifeq ($(ARCH), mips)
	@echo "32-bit MIPS platform"
else
	@echo "unknown platform"
endif
	@echo

